cc_test(
    name = "counter_aggregator_test",
    srcs = [
        "counter_aggregator_test.cc",
    ],
    deps = [
        "//sdk/src/metrics",
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "histogram_aggregator_test",
    srcs = [
        "histogram_aggregator_test.cc",
    ],
    deps = [
        "//sdk/src/metrics",
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "metric_instrument_test",
    srcs = [
        "metric_instrument_test.cc",
    ],
    deps = [
        "//sdk/src/metrics",
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "controller_test",
    srcs = [
        "controller_test.cc",
    ],
    deps = [
        "//sdk/src/metrics",
	"//exporters/ostream:ostream_metrics_exporter",
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "meter_test",
    srcs = [
        "meter_test.cc",
    ],
    deps = [
        "//sdk/src/metrics",
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "record_test",
    srcs = [
        "record_test.cc",
    ],
    deps = [
        "//sdk/src/metrics",
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "sketch_aggregator_test",
    srcs = [
        "sketch_aggregator_test.cc",
    ],
    deps = [
        "//sdk/src/metrics",
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "ungrouped_processor_test",
    srcs = [
        "ungrouped_processor_test.cc",
    ],
    deps = [
        "//sdk/src/metrics",
        "@com_google_googletest//:gtest_main",
    ],
)
