cc_test(
    name = "aggregator_test",
    srcs = [
        "aggregator_test.cc",
    ],
    deps = [
        "//sdk/src/metrics",
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "metric_instrument_test",
    srcs = [
        "metric_instrument_test.cc",
    ],
    deps = [
        "//sdk/src/metrics",
        "@com_google_googletest//:gtest_main",
    ],
)
